### ISSUE TITLE
Text typed in is not readable

### ISSUE THREAD

**Issue by dave39339** [tubaguner/BMI-Calculator#2]
The input fields display '~' characters instead of the ones that are actually typed by the user. They seem to behave similar to a password input box. I am not sure if this is intended. I can provide screenshots if required.

(Tested on Ubuntu22.04.2 LTS + Python3)

**Comment by tubaguner** [comment]
Yes, they were very well intended, as I wanted it to be secretive and fancy, because maybe some people wouldn't want others peering into the screen to see them entering their weight/height haha. The main issue is with the result variable. I'm trying to get the calculation output appear on the result entry.

**Comment by dave39339** [comment]
I assume this is not relevant anymore. :)
